name: Continous Integration and Development

on:
    push:
        branches:
            - main

env:
    DOTNET_VERSION: '8.0.x'

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Azure

        steps:
            - name: Checkout code ✨
              uses: actions/checkout@v4

            - name: Setup dotnet 8
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            
            # dotnet is already installed, we can just use run
            - name: Restore dependencies ♻
              run: dotnet restore Weather-API

            - name: Build App 🛠
              run: dotnet build -c Release --no-restore Weather-API/CICD.sln

            #- name: Automated Tests
            #  run: dotnet test Weather.Tests -c Release --no-build

            - name: Publish App
              run: dotnet publish -c Release -o ./out Weather-API/CICD.sln

